version: "3"
services:
  postgres:
    image: postgres:10.1
    command: postgres -c max_connections=500
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis
    ports:
      - "6379:6379"
  bull-queue-ui:
    image: registry.gitlab.com/vidhunv1/bull-queue-ui:dev
    ports:
      - "4567:4567"