 version: "3"
 services:
   postgres:
     image: postgres:10.1
     command: postgres -c max_connections=500
     ports:
       - "5432:5432"
     environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
   redis:
     image: redis
     ports:
       - "6379:6379"
