export enum CryptoCurrency {
  BTC = 'BTC'
}

export enum FiatCurrency {
  RUB = 'RUB',
  NGN = 'NGN',
  CNY = 'CNY',
  INR = 'INR',
  USD = 'USD',
  GBP = 'GBP',
  VEF = 'VEF',
  EUR = 'EUR',
  COP = 'COP',
  ZAR = 'ZAR',
  SEK = 'SEK',
  SGD = 'SGD',
  THB = 'THB',
  HKD = 'HKD',
  AUD = 'AUD',
  UAH = 'UAH',
  MYR = 'MYR',
  PEN = 'PEN',
  CAD = 'CAD',
  MXN = 'MXN',
  BRL = 'BRL',
  PAB = 'PAB',
  CLP = 'CLP',
  PKR = 'PKR',
  KES = 'KES',
  NZD = 'NZD',
  SAR = 'SAR',
  PHP = 'PHP',
  VND = 'VND',
  AED = 'AED',
  ARS = 'ARS',
  RON = 'RON',
  IRR = 'IRR',
  BYN = 'BYN',
  KZT = 'KZT',
  TRY = 'TRY',
  NOK = 'NOK',
  DOP = 'DOP',
  MAD = 'MAD',
  GHS = 'GHS',
  PLN = 'PLN',
  CRC = 'CRC',
  UGX = 'UGX',
  TZS = 'TZS',
  LKR = 'LKR',
  KRW = 'KRW',
  HRK = 'HRK',
  JPY = 'JPY'
}
